### ISSUE TITLE
Errors on POINT EMPTY (Java)

### ISSUE THREAD

**Issue by jagill** [bjornharrtell/flatgeobuf#17]
Empty versions of each of the geometry types are valid geometries, whose WKTs are of the form `"POINT EMPTY"`, `"MULTIPOLYGON EMPTY"`, etc.  I added Java tests for each of them (except for `GEOMETRYCOLLECTION`), which all passed except `"POINT EMPTY"` (stack trace below).

This may be related to the fact that empty points cannot be serialized into (strict) WKB, with the rough reasoning that any other empty geometry can just have the list of points/geometries be empty, which doesn't work for points.  A standard workaround (done by ESRI, EWKB, etc) is to use `NaN`s for the coordinates for empty points.

Would flatgeobuf be interested in supporting this use case?

```
java.lang.ArrayIndexOutOfBoundsException: 0

	at org.wololo.flatgeobuf.geotools.GeometryConversions.deserialize(GeometryConversions.java:114)
	at org.wololo.flatgeobuf.geotools.FeatureConversions.deserialize(FeatureConversions.java:86)
	at org.wololo.flatgeobuf.geotools.FeatureCollectionConversions.deserialize(FeatureCollectionConversions.java:153)
	at org.wololo.flatgeobuf.test.GeometryRoundtripTest.roundTrip(GeometryRoundtripTest.java:91)
	at org.wololo.flatgeobuf.test.GeometryRoundtripTest.pointEmpty(GeometryRoundtripTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by bjornharrtell** [comment]
My original intent was to *not* provide support for both null and empty geometries. I changed my mind about null geometries some time ago but not about empty geometries. As I have the geometry type as part of the header (or geometry) a null geometry has a known type so providing any other encoding support seem redundant to me but perhaps I'm missing something here.

**Comment by bjornharrtell** [comment]
Mabye there is spec/encoding issue here, just the bug in #18 that you fixed? :)
